#!/bin/bash

LVER=$1
TAG=${2:-16}
NAME=$(basename $PWD)
if [ -z "$TAG" -o "$TAG" = -h ]; then
  echo Usage: $0 TAG
  exit 0
fi
cat dockerfile-$TAG | sed s"/%LSSTVERSION%/$LVER/g" > fix-dockerfile-$LVER-$TAG
echo Building $NAME
FULLNAME=$NAME-$LVER:$TAG
LOG=$FULLNAME.log
docker build --no-cache --progress=plain -t $FULLNAME -f fix-dockerfile-$LVER-$TAG . 2>&1 | tee $LOG
