#!/bin/bash

LVER=$1
TAG=${2:-06}
NAME=$(basename $PWD)
if [ -z "$TAG" -o "$TAG" = -h ]; then
  echo Usage: $0 TAG
  exit 0
fi
cat dockerfile-$TAG | sed s"/%LSSTVERSION%/$LVER/g" > fix-dockerfile-$LVER-$TAG
echo Building $NAME
docker build --no-cache -t "$NAME-$LVER:$TAG" -f fix-dockerfile-$LVER-$TAG .
