from lsstsqre/centos:7-stack-lsst_distrib-%LSSTVERSION%

USER root
RUN  yum --assumeyes --quiet install vim
USER lsst

RUN echo source /opt/lsst/software/stack/loadLSST.bash >setup.sh
RUN echo setup lsst_distrib >>setup.sh
RUN echo "export PS1='lsst:%LSSTVERSION%> '" >> setup.sh
RUN echo "export LSSTVERSION='%LSSTVERSION%'" >> setup.sh
RUN echo "export OMP_NUM_THREADS=1" >> setup.sh
RUN echo "export NUMEXPR_MAX_THREADS=1" >> setup.sh

RUN source setup.sh &&\
    conda create -y --prefix parslenv &&\
    conda activate $parslenv &&\
    #conda install -n base conda-libmamba-solver &&\
    #conda config --set solver libmamba &&\
    pip install git+https://github.com/LSSTDESC/desc-gen3-prod.git &&\
    g3wf-install-parsl-w2332

RUN echo "conda activate parslenv" >>  setup.sh
