#!/bin/bash

# g3wfpipe-run
#
# David Adams
# May 2023

THISBAS=$(basename $0)
THISPTH=$0
ARGS="$*"

# There were warnings in the QG generation.
echo $THISBAS: NUMEXPR_MAX_THREADS=$NUMEXPR_MAX_THREADS

if echo $ARGS | grep proc >/dev/null; then
  SYMFIL='./sysmon.csv'
  FRQFIL='./frqmon.csv'
  if test -r $SYMFIL; then
    echo $THISBAS: Sysmon file $SYMFIL already exists.
    exit 0
  else
    echo $THISBAS: Starting sysmon
    desc-sysmon-reporter "fnam='$SYMFIL';log='sysmon.log';dt=5;frqfnam='$FRQFIL'" &
    PID=$!
    echo $PID>sysmon.pid
  fi
fi
echo $THISBAS: Starting workflow script with args $ARGS
$THISPTH.py $ARGS
