#!/bin/bash

MYNAME=$(basename ${BASH_SOURCE[0]})
LNAM=$1
HELP=
if [ "$LNAM" = "-h" ]; then
  HELP=true
elif [ "$LNAM" = "-v" ]; then
  shift
  IVER=$1
  shift
  LNAM=$1
else
  IVER=18
fi
if [ -n "$HELP" ]; then
  echo Usage: source $MYNAME [-v IMAGE-VERSION] LSST_VERSION
  exit 0
fi

LVER=$(g3wf-convert-lsst-version $LNAM)
if [ -z "$LVER" ]; then
  echo ERROR: $MYNAME: Invalid version nickname: $LNAM
  exit 3
fi

shift
COM="$*"
export PS1="Failed $MYNAME> "

USERS=$(whoami)
if [ $USERS != dladams ]; then
  USERS="$USERS dladams"
fi

for USER in $USERS; do
  IMG=$USER/gen3workflow-$LVER:$IVER
  if shifterimg images | grep $IMG 2>&1 1>/dev/null; then
    BADIMGS=
    break
  else
    BADIMGS="$BADIMGS $IMG"
  fi
done

if [ -n "$BADIMGS" ]; then
  echo Unable to find a matching shifter image:
  for IMG in $BADIMGS; do
    echo "  $IMG"
  done
  exit 4
fi

echo $MYNAME: Loading shifter image $IMG
export PS1="shifter $LVER> "
if [ -z "$COM" ]; then
  COM=/bin/bash
else
  echo $MYNAME: Running command $COM
fi
CFIL=$(pwd)/shifter-command
echo "#!/bin/bash" >$CFIL
echo source /opt/lsst/software/stack/setup.sh >>$CFIL
echo $COM >>$CFIL
chmod +x $CFIL
shifter --image=$IMG $CFIL
