#!/bin/bash

LNAM=$1
LVER=$(g3wf-convert-lsst-version $LNAM)
if [ -z "$LVER" ]; then
  err_echo ERROR: Invalid config field: $OPT
  exit 3
fi
shift
COM="$*"
MYNAME=$(basename ${BASH_SOURCE[0]})
export PS1="Failed $MYNAME> "
IVER=07

if [ -z "$LVER" ]; then
  echo Usage: source $MYNAME LSST_VERSION
else
  IMG=$(whoami)/gen3workflow-$LVER:$IVER
  echo $MYNAME: Loading shifter image $IMG
  export PS1="shifter $LVER> "
  if [ -z "$COM" ]; then
    COM=/bin/bash
  else
    echo $MYNAME: Running command $COM
  fi
  CFIL=$(pwd)/shifter-command
  echo "#!/bin/bash" >$CFIL
  echo source /opt/lsst/software/stack/setup.sh >>$CFIL
  echo $COM >>$CFIL
  chmod +x $CFIL
  shifter --image=$IMG $CFIL
fi

