#!/bin/bash

# g3wf-check-cvmfs
#
# David Adams
# August 2023
#
# Source script to check if a cvmfs-based desc-ge3-prod env is installed.
#
# Called with argument LVERTAG:OPT
# where LVERTAG is an LSST release tag nickname (e.g. w2321, see
# g3wf-convert-lsst-version) and OPT indicates which package to
# install on top of that release.
# If successful, 0 is returned and the SW location is written to stdout.

LVEROPT=$1
LVERTAG=$(echo $LVEROPT | cut -d':' -f1)
LVER=$(g3wf-convert-lsst-version $LVERTAG)
OPT=$(echo $LVEROPT | grep : | cut -d':' -f2-)
if [[ -z $OPT ]]; then OPT=parsl; fi
MYNAME=$(basename ${BASH_SOURCE[0]})
export PS1="Failed $MYNAME> "

if [ -z "$LVER" -o "$LVER" = "-h" -o -z "$OPT" ]; then
  echo Usage: source $MYNAME LSST_TAG:OPT >&2
elif [ -z "$LVER" ]; then
  echo $MYNAME: ERROR: Unable to interpret LSST tag $LVERTAG >&2
elif ! outbase=$(descprod-output-dir create installs); then
  echo $MYNAME: ERROR: Unable to find decprod output dir. >&2
else
  cnam=g3wf-$LVERTAG-$OPT
  wq_env=$outbase/$cnam
  if [ -r $wq_env ]; then
    echo $wq_env
    exit 0
  else
    echo $MYNAME: Unable to find conda env $wq_env >&2
  fi
fi
exit 1
